language: go

sudo: false

go:
  - 1.8

before_install:
  - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.4.6-1_amd64.deb"
  - dpkg -x shellcheck_0.4.6-1_amd64.deb $HOME
  - export PATH=$HOME/usr/bin:$PATH
  - go get -u github.com/signalfx/gobuild
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gem install mdl

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - export GOCOVERDIR_DIR="."
  - ./scripts/travis_check.sh
