[vars]
  ignoreDirs = [".git", "vendor"]
  duplLimit = "300"
  testCoverage = 100.0
  testFlags = ["-covermode", "atomic", "-race", "-timeout", "120s", "-cpu", "4", "-parallel", "8"]

[metalinter]
  [metalinter.vars]
    args = ["-t", "--disable-all", "--vendor", "--min-confidence=.3", "--deadline=300s"]
  [metalinter.ignored]
    coverageignored = "ignored is unused"
  [metalinter.enabled]
    golint = true
    gofmt = true
    varcheck = true
    maligned = true
    gocyclo = true
    vet = true
    deadcode = true
    unconvert = true
    structcheck = true
    ineffassign = true
    errcheck = true
